"""
===============================================================================
HDBSCAN VISUALIZATION
===============================================================================

Project
-------
Analisis Zona Rawan dan Area Terbakar Kebakaran Hutan dan Lahan
Menggunakan HDBSCAN dan XGBoost Berbasis Data Hotspot FIRMS
dan Citra Sentinel-2 di Kabupaten Ketapang Tahun 2025–2026

Description
-----------
This script visualizes the outputs generated by the HDBSCAN analysis
pipeline without re-running the clustering process.

Input Files
-----------
- clustered_dataset.csv
- cluster_interpretation.csv
- cluster_profile.csv
- Ketapang administrative boundary (shapefile)

Outputs
--------
Maps
-----
01_original_hotspot_map.png
02_hdbscan_cluster_map.png
03_activity_rank_map.png
04_wildfire_risk_map.png

Charts
-------
05_cluster_distribution.png
06_risk_distribution.png
07_hotspot_frp_relationship.png

Dashboard
----------
08_summary_dashboard.png

Author
------
Zahra Aura Hisani

===============================================================================
"""

# =============================================================================
# IMPORT LIBRARIES
# =============================================================================

from pathlib import Path
import logging

import numpy as np
import pandas as pd

import geopandas as gpd

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from matplotlib.lines import Line2D

# =============================================================================
# PROJECT PATH
# =============================================================================
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]

RESULT_DIR = PROJECT_ROOT / "data" / "results" / "hdbscan"

OUTPUT_DIR = PROJECT_ROOT / "outputs"

MAP_OUTPUT_DIR = OUTPUT_DIR / "maps"

VIS_OUTPUT_DIR = OUTPUT_DIR / "visualization"

# =============================================================================
# INPUT FILES
# =============================================================================

CLUSTERED_DATASET_FILE = RESULT_DIR / "clustered_dataset.csv"

CLUSTER_PROFILE_FILE = RESULT_DIR / "cluster_profile.csv"

CLUSTER_INTERPRETATION_FILE = RESULT_DIR / "cluster_interpretation.csv"
# =============================================================================
# SHAPEFILE
# =============================================================================

SHAPEFILE_PATH = (
    PROJECT_ROOT
    / "data"
    / "shapefile"
    / "ketapang_kecamatan.shp"
)

# =============================================================================
# OUTPUT DIRECTORIES
# =============================================================================

MAP_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

VIS_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

# =============================================================================
# MAP COLORS
# =============================================================================

RISK_COLOR = {
    "Very High": "#8B0000",
    "High": "#E31A1C",
    "Moderate": "#FD8D3C",
    "Low": "#FED976",
    "Very Low": "#31A354",
    "Noise": "#BDBDBD",
}

# =============================================================================
# MARKER STYLE
# =============================================================================

RISK_MARKER = {
    "Very High": "^",     # Triangle Up
    "High": "D",          # Diamond
    "Moderate": "o",      # Circle
    "Low": "s",           # Square
    "Very Low": "*",      # Star
    "Noise": "o",         # Circle
}

RISK_MARKER_SIZE = {
    "Very High": 90,
    "High": 80,
    "Moderate": 70,
    "Low": 60,
    "Very Low": 55,
    "Noise": 45,
}

RISK_EDGE_COLOR = "white"

RISK_EDGE_WIDTH = 0.6

RISK_ALPHA = 0.95

# =============================================================================
# MARKER DRAWING PRIORITY
# =============================================================================

RISK_ZORDER = {
    "Very High": 10,
    "High": 9,
    "Moderate": 8,
    "Low": 7,
    "Very Low": 6,
    "Noise": 5,
}

# =============================================================================
# FIGURE SETTINGS
# =============================================================================

FIGSIZE = (12, 10)

DPI = 300

POINT_SIZE = 6

BOUNDARY_COLOR = "black"

BOUNDARY_WIDTH = 0.8

# =============================================================================
# LOGGING
# =============================================================================

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
)

logger = logging.getLogger(__name__)

logger.info("=" * 80)
logger.info("HDBSCAN VISUALIZATION")
logger.info("=" * 80)

# =============================================================================
# LOAD DATA
# =============================================================================

def load_visualization_data():
    """
    Load HDBSCAN outputs and prepare spatial visualization dataset.

    Returns
    -------
    tuple
        clustered_gdf : GeoDataFrame
        cluster_profile : DataFrame
        cluster_interpretation : DataFrame
    """

    logger.info("=" * 80)
    logger.info("LOADING VISUALIZATION DATA")
    logger.info("=" * 80)

    # -------------------------------------------------------------------------
    # Check Input Files
    # -------------------------------------------------------------------------

    input_files = [
        CLUSTERED_DATASET_FILE,
        CLUSTER_INTERPRETATION_FILE,
        CLUSTER_PROFILE_FILE,
    ]

    for file in input_files:

        if not file.exists():

            raise FileNotFoundError(
                f"Required file not found:\n{file}"
            )

        logger.info("Found : %s", file.name)

    # -------------------------------------------------------------------------
    # Read CSV Files
    # -------------------------------------------------------------------------

    clustered_dataset = pd.read_csv(
        CLUSTERED_DATASET_FILE
    )

    cluster_profile = pd.read_csv(
        CLUSTER_PROFILE_FILE
    )

    cluster_interpretation = pd.read_csv(
        CLUSTER_INTERPRETATION_FILE
    )

    logger.info(
        "Clustered Dataset : %d records",
        len(clustered_dataset),
    )

    logger.info(
        "Cluster Profile : %d clusters",
        len(cluster_profile),
    )

    logger.info(
        "Cluster Interpretation : %d clusters",
        len(cluster_interpretation),
    )

    # -------------------------------------------------------------------------
    # Merge Interpretation
    # -------------------------------------------------------------------------

    logger.info(
        "Merging clustered dataset with interpretation..."
    )

    clustered_dataset = clustered_dataset.merge(
        cluster_interpretation,
        on="Cluster",
        how="left",
        validate="many_to_one",
    )

    missing = clustered_dataset["Risk_Level"].isna().sum()

    if missing > 0:

        logger.warning(
            "%d pixels have no interpretation.",
            missing,
        )

    else:

        logger.info(
            "All pixels successfully merged."
        )

    # -------------------------------------------------------------------------
    # Create GeoDataFrame
    # -------------------------------------------------------------------------

    logger.info(
        "Creating GeoDataFrame..."
    )

    clustered_gdf = gpd.GeoDataFrame(
        clustered_dataset,
        geometry=gpd.points_from_xy(
            clustered_dataset["longitude"],
            clustered_dataset["latitude"],
        ),
        crs="EPSG:4326",
    )

    logger.info(
        "GeoDataFrame created successfully."
    )

    logger.info(
        "Coordinate Reference System : %s",
        clustered_gdf.crs,
    )

    # -------------------------------------------------------------------------
    # Dataset Summary
    # -------------------------------------------------------------------------

    logger.info("-" * 80)

    logger.info(
        "Total Pixels : %d",
        len(clustered_gdf),
    )

    logger.info(
        "Unique Clusters : %d",
        clustered_gdf["Cluster"].nunique(),
    )

    logger.info(
        "Risk Levels : %s",
        ", ".join(
            clustered_gdf["Risk_Level"]
            .dropna()
            .unique()
            .tolist()
        ),
    )

    logger.info("-" * 80)

    return (
        clustered_gdf,
        cluster_profile,
        cluster_interpretation,
    )

# =============================================================================
# LOAD ADMINISTRATIVE BOUNDARY
# =============================================================================

def load_administrative_boundary():
    """
    Load Ketapang administrative boundary.

    Returns
    -------
    GeoDataFrame
        Administrative boundary.
    """

    logger.info("=" * 80)
    logger.info("LOADING ADMINISTRATIVE BOUNDARY")
    logger.info("=" * 80)

    if not SHAPEFILE_PATH.exists():

        raise FileNotFoundError(
            f"Shapefile not found:\n{SHAPEFILE_PATH}"
        )

    boundary = gpd.read_file(
        SHAPEFILE_PATH
    )

    if boundary.crs != "EPSG:4326":

        logger.info(
            "Reprojecting boundary to EPSG:4326..."
        )

        boundary = boundary.to_crs(
            "EPSG:4326"
        )

    logger.info(
        "Boundary loaded successfully."
    )

    logger.info(
        "Total polygons : %d",
        len(boundary),
    )

    logger.info(
        "CRS : %s",
        boundary.crs,
    )

    logger.info(
        "Boundary extent:"
    )

    logger.info(
        "MinX : %.6f",
        boundary.total_bounds[0],
    )

    logger.info(
        "MinY : %.6f",
        boundary.total_bounds[1],
    )

    logger.info(
        "MaxX : %.6f",
        boundary.total_bounds[2],
    )

    logger.info(
        "MaxY : %.6f",
        boundary.total_bounds[3],
    )

    return boundary

# =============================================================================
# CREATE BASE MAP
# =============================================================================

def create_base_map(
    boundary: gpd.GeoDataFrame,
):
    """
    Create standardized map canvas.

    Parameters
    ----------
    boundary : GeoDataFrame

    Returns
    -------
    tuple
        fig, ax
    """

    fig, ax = plt.subplots(
        figsize=FIGSIZE,
    )

    boundary.plot(
        ax=ax,
        facecolor="whitesmoke",
        edgecolor=BOUNDARY_COLOR,
        linewidth=BOUNDARY_WIDTH,
        zorder=1,
    )

    ax.set_xlabel("Longitude")

    ax.set_ylabel("Latitude")

    ax.set_aspect("equal")

    
    ax.grid(

    color="gray",

    linestyle=":",

    linewidth=0.5,

    alpha=0.35,

    )

    return fig, ax

# =============================================================================
# NORTH ARROW
# =============================================================================

def add_north_arrow(ax):
    """
    Add north arrow to map.
    """

    ax.annotate(
        "N",
        xy=(0.95, 0.95),
        xytext=(0.95, 0.82),
        xycoords="axes fraction",
        textcoords="axes fraction",
        ha="center",
        va="center",
        fontsize=14,
        fontweight="bold",
        arrowprops=dict(
            arrowstyle="-|>",
            color="black",
            linewidth=2,
        ),
    )

# =============================================================================
# FOOTER
# =============================================================================

def add_footer(fig):
    """
    Add figure footer.
    """

    fig.text(
        0.5,
        0.02,
        (
            "Source : VIIRS Hotspot (NASA FIRMS), "
            "HDBSCAN Analysis, Kabupaten Ketapang (2025–2026)"
        ),
        ha="center",
        fontsize=8,
    )

# =============================================================================
# PLOT RISK MARKERS
# =============================================================================
def plot_risk_markers(
    ax,
    subset,
    risk,
):
    """
    Plot wildfire hotspot markers.
    """

    if subset.empty:

        return

    if risk not in RISK_MARKER:

        raise ValueError(
            f"Unknown Risk Level : {risk}"
        )

    x_plot, y_plot = apply_marker_offset(
        subset
    )

    ax.scatter(

        x_plot,

        y_plot,

        marker=RISK_MARKER[risk],

        s=RISK_MARKER_SIZE[risk],

        c=RISK_COLOR[risk],

        edgecolors=RISK_EDGE_COLOR,

        linewidths=RISK_EDGE_WIDTH,

        alpha=RISK_ALPHA,

        zorder=RISK_ZORDER[risk],

    )

# =============================================================================
# ORIGINAL HOTSPOT MAP
# =============================================================================

def create_original_hotspot_map(
    clustered_gdf,
    boundary,
):
    """
    Create original hotspot distribution map.
    """

    logger.info("=" * 80)
    logger.info("CREATING ORIGINAL HOTSPOT MAP")
    logger.info("=" * 80)

    fig, ax = create_base_map(
        boundary
    )

    clustered_gdf.plot(
        ax=ax,
        color="red",
        markersize=POINT_SIZE,
        alpha=0.70,
        zorder=3,
    )

    ax.set_title(

    (
        "Wildfire Risk Map\n"
        "Kabupaten Ketapang (2025–2026)"
    ),

    fontsize=17,

    fontweight="bold",

    pad=18,

    loc="center",

    )

    add_north_arrow(ax)

    add_footer(fig)

    legend = [
        Line2D(
            [],
            [],
            marker="o",
            color="w",
            label="Hotspot",
            markerfacecolor="red",
            markersize=8,
        )
    ]

    ax.legend(
        handles=legend,
        loc="lower left",
    )

    output = (
        MAP_OUTPUT_DIR
        / "01_original_hotspot_map.png"
    )

    plt.savefig(

    output,

    dpi=DPI,

    bbox_inches="tight",

    pad_inches=0.25,

    )

    logger.info(
        "Saved : %s",
        output.name,
    )

    plt.close(fig)

# =============================================================================
# HDBSCAN CLUSTER MAP
# =============================================================================

def create_cluster_map(
    clustered_gdf,
    boundary,
):
    """
    Create HDBSCAN cluster map.
    """

    logger.info("=" * 80)
    logger.info("CREATING HDBSCAN CLUSTER MAP")
    logger.info("=" * 80)

    fig, ax = create_base_map(
        boundary
    )

    # -------------------------------------------------------------------------
    # Separate Noise and Valid Clusters
    # -------------------------------------------------------------------------

    noise = clustered_gdf[
        clustered_gdf["Cluster"] == -1
    ]

    clusters = clustered_gdf[
        clustered_gdf["Cluster"] != -1
    ]

    # -------------------------------------------------------------------------
    # Plot Valid Clusters
    # -------------------------------------------------------------------------

    clusters.plot(
        ax=ax,
        column="Cluster",
        cmap="nipy_spectral",
        markersize=POINT_SIZE,
        alpha=0.80,
        legend=False,
        zorder=3,
    )

    # -------------------------------------------------------------------------
    # Plot Noise
    # -------------------------------------------------------------------------

    if len(noise) > 0:

        noise.plot(
            ax=ax,
            color="lightgray",
            markersize=POINT_SIZE,
            alpha=0.60,
            zorder=2,
        )

    # -------------------------------------------------------------------------
    # Title
    # -------------------------------------------------------------------------

    ax.set_title(
        (
            "HDBSCAN Spatial Clustering Result\n"
            "Kabupaten Ketapang (2025–2026)"
        ),
        fontsize=15,
        fontweight="bold",
        pad=15,
    )

    # -------------------------------------------------------------------------
    # Decorations
    # -------------------------------------------------------------------------

    add_north_arrow(ax)

    add_footer(fig)

    legend = [

        Line2D(
            [],
            [],
            marker="o",
            color="w",
            markerfacecolor="purple",
            markersize=8,
            label="HDBSCAN Cluster",
        ),

        Line2D(
            [],
            [],
            marker="o",
            color="w",
            markerfacecolor="lightgray",
            markersize=8,
            label="Noise",
        ),

    ]

    ax.legend(
        handles=legend,
        loc="lower left",
    )

    output = (
        MAP_OUTPUT_DIR
        / "02_hdbscan_cluster_map.png"
    )

    plt.savefig(
        output,
        dpi=DPI,
        bbox_inches="tight",
    )

    logger.info(
        "Saved : %s",
        output.name,
    )

    plt.close(fig)

# =============================================================================
# ACTIVITY RANK MAP
# =============================================================================

def create_activity_rank_map(
    clustered_gdf,
    boundary,
):
    """
    Create wildfire activity ranking map.
    """

    logger.info("=" * 80)
    logger.info("CREATING ACTIVITY RANK MAP")
    logger.info("=" * 80)

    fig, ax = create_base_map(boundary)

    # -------------------------------------------------------------------------
    # Remove Noise
    # -------------------------------------------------------------------------

    ranked = clustered_gdf[
        clustered_gdf["Risk_Level"] != "Noise"
    ].copy()

    noise = clustered_gdf[
        clustered_gdf["Risk_Level"] == "Noise"
    ].copy()

    # -------------------------------------------------------------------------
    # Plot Ranked Clusters
    # -------------------------------------------------------------------------

    ranked.plot(
        ax=ax,
        column="Activity_Rank",
        cmap="RdYlGn_r",
        markersize=POINT_SIZE,
        alpha=0.80,
        legend=True,
        legend_kwds={
            "label": "Activity Rank",
            "shrink": 0.75,
        },
        zorder=3,
    )

    # -------------------------------------------------------------------------
    # Plot Noise
    # -------------------------------------------------------------------------

    if len(noise) > 0:

        noise.plot(
            ax=ax,
            color="lightgray",
            markersize=POINT_SIZE,
            alpha=0.40,
            zorder=2,
        )

    # -------------------------------------------------------------------------
    # Title
    # -------------------------------------------------------------------------

    ax.set_title(
        (
            "Wildfire Activity Ranking\n"
            "Kabupaten Ketapang (2025–2026)"
        ),
        fontsize=15,
        fontweight="bold",
        pad=15,
    )

    # -------------------------------------------------------------------------
    # Decorations
    # -------------------------------------------------------------------------

    add_north_arrow(ax)

    add_footer(fig)

    output = (
        MAP_OUTPUT_DIR
        / "03_activity_rank_map.png"
    )

    plt.savefig(
        output,
        dpi=DPI,
        bbox_inches="tight",
    )

    logger.info(
        "Saved : %s",
        output.name,
    )

    plt.close(fig)

# =============================================================================
# WILDFIRE RISK MAP
# =============================================================================
# =============================================================================
# WILDFIRE RISK MAP
# =============================================================================

def create_wildfire_risk_map(
    clustered_gdf,
    boundary,
):
    """
    Create wildfire risk map using interpreted HDBSCAN clusters.

    Marker positions are visually adjusted to reduce overlap while
    preserving the original hotspot coordinates.
    """

    logger.info("=" * 80)
    logger.info("CREATING WILDFIRE RISK MAP")
    logger.info("=" * 80)

    # -------------------------------------------------------------------------
    # Create Base Map
    # -------------------------------------------------------------------------

    fig, ax = create_base_map(
        boundary
    )

    # -------------------------------------------------------------------------
    # Risk Drawing Order
    # -------------------------------------------------------------------------

    risk_order = [

        "Very High",

        "High",

        "Moderate",

        "Low",

        "Very Low",

        "Noise",

    ]

    # -------------------------------------------------------------------------
    # Legend Container
    # -------------------------------------------------------------------------

    legend_handles = []

    # -------------------------------------------------------------------------
    # Draw Every Risk Level
    # -------------------------------------------------------------------------

    for risk in risk_order:

        subset = clustered_gdf[
            clustered_gdf["Risk_Level"] == risk
        ]

        if subset.empty:

            continue

        # -------------------------------------------------------------
        # Plot Marker
        # -------------------------------------------------------------

        plot_risk_markers(

            ax=ax,

            subset=subset,

            risk=risk,

        )

        # -------------------------------------------------------------
        # Legend
        # -------------------------------------------------------------

        legend_handles.append(

            Line2D(

                [],

                [],

                linestyle="",

                marker=RISK_MARKER[risk],

                markerfacecolor=RISK_COLOR[risk],

                markeredgecolor=RISK_EDGE_COLOR,

                markeredgewidth=RISK_EDGE_WIDTH,

                markersize=np.sqrt(
                    RISK_MARKER_SIZE[risk]
                ),

                label=risk,

            )

        )

        ax.set_title(
        (
            "Wildfire Risk Level Map\n"
            "Kabupaten Ketapang (2025–2026)"
        ),
        fontsize=16,
        fontweight="bold",
        pad=15,
    )

    add_north_arrow(ax)

    add_footer(fig)

    ax.legend(
        handles=legend_handles,
        title="Risk Level",
        loc="lower left",
        frameon=True,
    )

    output = MAP_OUTPUT_DIR / "04_wildfire_risk_map.png"

    plt.savefig(
        output,
        dpi=DPI,
        bbox_inches="tight",
        pad_inches=0.25,
    )

    logger.info(
        "Saved : %s",
        output.name,
    )

    plt.close(fig)

       
# =============================================================================
# ADAPTIVE MARKER OFFSET
# =============================================================================
def apply_marker_offset(
    subset,
    radius=0.00015,
):
    """
    Apply deterministic circular offsets for overlapping markers.

    The original hotspot coordinates remain unchanged.
    Only marker positions during plotting are shifted.
    """

    if len(subset) <= 1:

        return (
            subset.geometry.x.to_numpy(),
            subset.geometry.y.to_numpy(),
        )

    x = subset.geometry.x.to_numpy(dtype=float)

    y = subset.geometry.y.to_numpy(dtype=float)

    x_plot = x.copy()

    y_plot = y.copy()

    processed = np.zeros(
        len(subset),
        dtype=bool,
    )

    tolerance = radius * 0.50

    for i in range(len(subset)):

        if processed[i]:

            continue

        dx = x - x[i]

        dy = y - y[i]

        distance = np.sqrt(
            dx ** 2 + dy ** 2
        )

        neighbours = np.where(
            distance < tolerance
        )[0]

        if len(neighbours) == 1:

            processed[i] = True

            continue

        angles = np.linspace(
            0,
            2 * np.pi,
            len(neighbours),
            endpoint=False,
        )

        for idx, angle in zip(
            neighbours,
            angles,
        ):

            x_plot[idx] += (
                radius * np.cos(angle)
            )

            y_plot[idx] += (
                radius * np.sin(angle)
            )

            processed[idx] = True

    return (
        x_plot,
        y_plot,
    )

# =============================================================================
# CLUSTER STATISTICS
# =============================================================================

def create_cluster_statistics(
    cluster_summary,
    cluster_interpretation,
):
    """
    Create statistical summary of HDBSCAN clusters.
    """

    logger.info("=" * 80)
    logger.info("CREATING CLUSTER STATISTICS")
    logger.info("=" * 80)

    fig, axes = plt.subplots(
        1,
        3,
        figsize=(18,6),
    )

    # -------------------------------------------------------------------------
    # Cluster Distribution
    # -------------------------------------------------------------------------
    profile = (
        cluster_summary[
            cluster_summary["Activity_Rank"].notna()
        ]
        .copy()
        .sort_values("Activity_Rank")
    )

    profile = (
    cluster_summary[
        cluster_summary["Activity_Rank"].notna()
    ]
    .copy()
    .sort_values("Activity_Rank")
    )

    axes[0].bar(
        profile["Cluster"].astype(str),
        profile["Pixel_Count"],
    )

    axes[0].set_title(
        "Cluster Distribution"
    )

    axes[0].set_xlabel(
        "Cluster"
    )

    axes[0].set_ylabel(
        "Pixels"
    )

    # -------------------------------------------------------------------------
    # Risk Distribution
    # -------------------------------------------------------------------------

    risk_order = [
        "Very High",
        "High",
        "Moderate",
        "Low",
        "Very Low",
        "Noise",
    ]

    risk = (
        cluster_interpretation
        .groupby("Risk_Level")
        .size()
        .reindex(
            risk_order,
            fill_value=0,
        )
    )

    axes[1].bar(
        risk.index,
        risk.values,
    )

    axes[1].set_title(
        "Risk Level Distribution"
    )

    axes[1].tick_params(
        axis="x",
        rotation=45,
    )

    # -------------------------------------------------------------------------
    # FRP vs Hotspot
    # -------------------------------------------------------------------------

    axes[2].scatter(
        cluster_summary[
            "Mean_Hotspot_Frequency"
        ],
        cluster_summary[
            "Mean_FRP_Max"
        ],
        s=70,
    )

    axes[2].set_title(
        "FRP vs Hotspot"
    )

    axes[2].set_xlabel(
        "Mean Hotspot Frequency"
    )

    axes[2].set_ylabel(
        "Mean FRP"
    )

    plt.tight_layout()

    output = (
        VIS_OUTPUT_DIR
        / "05_cluster_statistics.png"
    )

    plt.savefig(
        output,
        dpi=DPI,
        bbox_inches="tight",
    )

    logger.info(
        "Saved : %s",
        output.name,
    )

    plt.close(fig)

# =============================================================================
# SUMMARY DASHBOARD
# =============================================================================

def create_summary_dashboard(
    clustered_gdf,
    cluster_summary,
    cluster_interpretation,
):
    """
    Create executive summary dashboard for HDBSCAN analysis.
    """

    logger.info("=" * 80)
    logger.info("CREATING SUMMARY DASHBOARD")
    logger.info("=" * 80)

    fig = plt.figure(
        figsize=(18,12),
        constrained_layout=True,
    )

    gs = fig.add_gridspec(
        3,
        3,
        height_ratios=[1,3,1],
    )

    # -------------------------------------------------------------------------
    # Summary Metrics
    # -------------------------------------------------------------------------

    ax_metrics = fig.add_subplot(gs[0,:])

    ax_metrics.axis("off")

    total_hotspot = len(clustered_gdf)

    total_cluster = (
        clustered_gdf["Cluster"]
        .loc[clustered_gdf["Cluster"] != -1]
        .nunique()
    )

    very_high = (
        cluster_interpretation["Risk_Level"]
        .eq("Very High")
        .sum()
    )

    summary = (
        f"Total Hotspots : {total_hotspot:,}\n"
        f"Total Clusters : {total_cluster}\n"
        f"Very High Risk Clusters : {very_high}"
    )

    ax_metrics.text(
        0.02,
        0.95,
        summary,
        fontsize=16,
        va="top",
        fontweight="bold",
    )

    # -------------------------------------------------------------------------
    # Cluster Distribution
    # -------------------------------------------------------------------------

    ax1 = fig.add_subplot(gs[1,0])

    profile = (
    cluster_summary[
        cluster_summary["Activity_Rank"].notna()
    ]
    .copy()
    )

    profile = profile.sort_values(
        "Activity_Rank"
    )

    ax1.set_title(
        "Cluster Distribution"
    )

    ax1.set_xlabel(
        "Activity Rank"
    )

    # -------------------------------------------------------------------------
    # Risk Distribution
    # -------------------------------------------------------------------------

    ax2 = fig.add_subplot(gs[1,1])

    risk = (
        cluster_interpretation
        .groupby("Risk_Level")
        .size()
    )

    ax2.bar(
        risk.index,
        risk.values,
    )

    ax2.tick_params(
        axis="x",
        rotation=45,
    )

    ax2.set_title(
        "Risk Distribution"
    )

    # -------------------------------------------------------------------------
    # FRP vs Hotspot
    # -------------------------------------------------------------------------

    ax3 = fig.add_subplot(gs[1,2])

    ax3.scatter(
        cluster_summary[
            "Mean_Hotspot_Frequency"
        ],
        cluster_summary[
            "Mean_FRP_Max"
        ],
        s=80,
    )

    ax3.set_xlabel(
        "Mean Hotspot"
    )

    ax3.set_ylabel(
        "Mean FRP"
    )

    ax3.set_title(
        "FRP vs Hotspot"
    )

    # -------------------------------------------------------------------------
    # Key Findings
    # -------------------------------------------------------------------------

    ax_note = fig.add_subplot(gs[2,:])

    ax_note.axis("off")

    top = (
        cluster_interpretation
        .sort_values("Activity_Rank")
        .iloc[0]
    )

    findings = (
        "Key Findings\n\n"
        f"• Highest priority cluster : {int(top['Cluster'])}\n"
        f"• Risk Level : {top['Risk_Level']}\n"
        f"• Mean Hotspot Frequency : "
        f"{top['Mean_Hotspot_Frequency']:.2f}\n"
        f"• Mean FRP : "
        f"{top['Mean_FRP_Max']:.2f}"
    )

    ax_note.text(
        0.01,
        0.98,
        findings,
        fontsize=13,
        va="top",
    )

    fig.suptitle(
        "HDBSCAN Wildfire Analysis Dashboard",
        fontsize=20,
        fontweight="bold",
    )

    output = (
        VIS_OUTPUT_DIR
        / "06_summary_dashboard.png"
    )

    plt.savefig(
        output,
        dpi=DPI,
        bbox_inches="tight",
    )

    logger.info(
        "Saved : %s",
        output.name,
    )

    plt.close(fig)

# =============================================================================
# MAIN VISUALIZATION PIPELINE
# =============================================================================

def main():
    """
    Execute complete HDBSCAN visualization pipeline.
    """

    logger.info("=" * 80)
    logger.info("START HDBSCAN VISUALIZATION PIPELINE")
    logger.info("=" * 80)

    start_time = pd.Timestamp.now()

    try:

        # ---------------------------------------------------------------------
        # Load Data
        # ---------------------------------------------------------------------

        clustered_gdf, cluster_profile, cluster_interpretation = (
            load_visualization_data()
        )

        # ---------------------------------------------------------------------
        # Merge Summary Data
        # ---------------------------------------------------------------------

        cluster_summary = cluster_profile.merge(
            cluster_interpretation[
                [
                    "Cluster",
                    "Activity_Rank",
                    "Risk_Level",
                ]
            ],
            on="Cluster",
            how="left",
        )
        print(cluster_summary[
            ["Cluster", "Activity_Rank", "Risk_Level"]
        ].head(20))

        print("\nJumlah NaN Activity_Rank:")
        print(cluster_summary["Activity_Rank"].isna().sum())

        print(cluster_summary.dtypes)
        
        logger.info(
            "Cluster summary successfully prepared."
        )

        # ---------------------------------------------------------------------
        # Load Boundary
        # ---------------------------------------------------------------------

        boundary = load_administrative_boundary()

        # ---------------------------------------------------------------------
        # Create Maps
        # ---------------------------------------------------------------------

        create_original_hotspot_map(
            clustered_gdf,
            boundary,
        )

        create_cluster_map(
            clustered_gdf,
            boundary,
        )

        create_activity_rank_map(
            clustered_gdf,
            boundary,
        )

        create_wildfire_risk_map(
            clustered_gdf,
            boundary,
        )
        
        # ---------------------------------------------------------------------
        # Create Statistical Visualization
        # ---------------------------------------------------------------------

        create_cluster_statistics(
            cluster_summary,
            cluster_interpretation,
        )

        create_summary_dashboard(
            clustered_gdf,
            cluster_summary,
            cluster_interpretation,
        )

        # ---------------------------------------------------------------------
        # Finish
        # ---------------------------------------------------------------------

        elapsed = (
            pd.Timestamp.now()
            - start_time
        )

        logger.info("=" * 80)
        logger.info("VISUALIZATION COMPLETED SUCCESSFULLY")
        logger.info("=" * 80)

        logger.info(
            "Execution Time : %s",
            elapsed,
        )

        logger.info(
            "Output Maps      : %s",
            MAP_OUTPUT_DIR,
        )

        logger.info(
            "Output Figures   : %s",
            VIS_OUTPUT_DIR,
        )

    except Exception as error:

        logger.exception(
            "Visualization pipeline failed."
        )

        raise error


# =============================================================================
# ENTRY POINT
# =============================================================================

if __name__ == "__main__":

    main()